version: '3.8'

services:
  ch-app:
    build:
      context: ..
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=info
    volumes:
      # Mount for development - remove in production
      - ../static:/app/static:ro
      - ../ch_app.html:/app/ch_app.html:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped